name: gabriel
favicon: null
layout_spectrum: 0.9459978695958853
typography_spectrum: 0.11630269442684948
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8dfce'
    - '#1e061e'
    - '#bec5b6'
    - '#88878d'
    - '#3d2e47'
  brandStrength: 0.4591710593085736
  lightness: 0.3998080757446587
  saturation: 0.5917903557419777
  rhythmicContrast: 0.7369476757012308
purpose: []
